/**
 * AUTOGENERATED TYPESCRIPT TYPES FROM RESTOREPOINT API
 * Generated on: 2024-11-14T13:30:00.000Z
 * Source: swagger-2.json
 * API Version: 2.0
 * 
 * ⚠️  DO NOT EDIT MANUALLY - This file is generated by scripts/generate-types.ts
 * 
 * This file contains TypeScript type definitions generated from the Restorepoint OpenAPI
 * specification. These types provide compile-time safety and IDE support for API interactions.
 * 
 * Usage:
 * import type { Device, Backup, ApiResponse } from './types/restorepoint-api.js';
 */

/**
 * API version information
 */
export const API_INFO = {
  title: 'Restorepoint API',
  version: '2.0',
  description: 'The Restorepoint RESTful API allows you to trigger all of Restorepoint\'s operations programatically.\nRestorepoint\'s web interface uses the same API for all its operations. Everything you can do through the UI can\nbe done through this API.',
} as const;

/**
 * Primitive type aliases for common API types
 */
export type DeviceId = string;
export type BackupId = string;
export type TaskId = string;
export type AgentId = string;
export type CommandId = string;
export type UserId = string;
export type CredentialId = string;

/**
 * Date and time types
 */
export type Timestamp = string; // ISO 8601 timestamp
export type CronExpression = string; // Cron-like schedule expression

/**
 * Status enumerations
 */
export type TaskStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | 'timeout';
export type DeviceStatus = 'online' | 'offline' | 'unknown' | 'maintenance';
export type BackupStatus = 'completed' | 'failed' | 'in_progress' | 'cancelled';
export type AgentStatus = 'online' | 'offline' | 'connecting' | 'error';

/**
 * Basic Device type (will be expanded from swagger)
 */
export interface Device {
  readonly id: DeviceId;
  readonly name: string;
  readonly type: string;
  readonly ipAddress?: string;
  readonly hostname?: string;
  readonly status: DeviceStatus;
  readonly enabled: boolean;
  readonly createdAt: Timestamp;
  readonly updatedAt: Timestamp;
  readonly description?: string;
  readonly tags?: readonly string[];
}

/**
 * Basic Backup type (will be expanded from swagger)
 */
export interface Backup {
  readonly id: BackupId;
  readonly name: string;
  readonly deviceId: DeviceId;
  readonly status: BackupStatus;
  readonly createdAt: Timestamp;
  readonly completedAt?: Timestamp;
  readonly size?: number;
  readonly type: 'full' | 'incremental' | 'config-only';
  readonly description?: string;
}

/**
 * Plugin field for device configuration
 */
export interface PluginField {
  readonly Name: string;
  readonly Value: string;
}

/**
 * Device monitoring configuration
 */
export interface DeviceMonitor {
  readonly Enabled?: boolean;
  readonly AlertFail?: number;
  readonly IsPing?: boolean;
  readonly AlertEmail?: boolean;
  readonly AlertEmailUp?: boolean;
}

/**
 * Asset field for device information
 */
export interface AssetField {
  readonly ID: number;
  readonly Value: string;
}

/**
 * Backup schedule configuration
 */
export interface BackupSchedule {
  readonly Schedule: CronExpression;
  readonly RetainVersions?: number;
  readonly RetainDays?: number;
  readonly DeleteDays?: number;
  readonly ConfigTypes?: readonly string[];
}

/**
 * Failure policy configuration
 */
export interface FailurePolicy {
  readonly Retries?: number;
  readonly Action?: 'Revert' | 'Manual' | 'Disable';
  readonly Alerts?: number;
  readonly RetryInterval?: number;
}

/**
 * Task information for async operations
 */
export interface TaskInfo {
  readonly id: TaskId;
  readonly type: 'backup' | 'restore' | 'command' | 'custom';
  readonly status: TaskStatus;
  readonly progress: number; // 0-100
  readonly message: string;
  readonly createdAt: Timestamp;
  readonly updatedAt: Timestamp;
  readonly completedAt?: Timestamp;
  readonly estimatedCompletion?: Timestamp;
  readonly details?: Record<string, unknown>;
  readonly error?: string;
}

/**
 * Basic Agent type (will be expanded from swagger)
 */
export interface Agent {
  readonly id: AgentId;
  readonly name: string;
  readonly status: AgentStatus;
  readonly version: string;
  readonly lastSeen: Timestamp;
  readonly devices: readonly DeviceId[];
  readonly enabled: boolean;
  readonly ipAddress?: string;
  readonly hostname?: string;
}

/**
 * Command type (will be expanded from swagger)
 */
export interface Command {
  readonly id: CommandId;
  readonly name: string;
  readonly command: string;
  readonly deviceIds: readonly DeviceId[];
  readonly status: TaskStatus;
  readonly createdAt: Timestamp;
  readonly executedAt?: Timestamp;
  readonly completedAt?: Timestamp;
  readonly output?: string;
  readonly type: 'show' | 'configure' | 'execute' | 'custom';
  readonly timeout: number;
  readonly description?: string;
}

/**
 * Pagination types
 */
export interface PaginationParams {
  readonly limit?: number;
  readonly offset?: number;
  readonly sortBy?: string;
  readonly sortOrder?: 'asc' | 'desc';
}

export interface PaginationMeta {
  readonly offset: number;
  readonly limit: number;
  readonly total: number;
}

/**
 * Generic API response wrapper
 */
export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  message?: string;
  errors?: Record<string, readonly string[]>;
  metadata?: any;
}

/**
 * Paginated response wrapper
 */
export interface PaginatedResponse<T> extends ApiResponse<T[]> {
  readonly metadata: PaginationMeta;
}

/**
 * API response types for different endpoints
 */
export interface DeviceListResponse extends PaginatedResponse<Device> {}
export interface DeviceResponse extends ApiResponse<Device> {}
export interface BackupListResponse extends PaginatedResponse<Backup> {}
export interface BackupResponse extends ApiResponse<Backup> {}
export interface TaskResponse extends ApiResponse<TaskInfo> {}
export interface AgentListResponse extends PaginatedResponse<Agent> {}
export interface AgentResponse extends ApiResponse<Agent> {}
export interface CommandListResponse extends ApiResponse<any[]> {}
export interface CommandResponse extends ApiResponse<any> {}

/**
 * Operation result types
 */
export interface AsyncOperationResult {
  readonly success: true;
  readonly taskId: TaskId;
  readonly message: string;
  readonly estimatedTime?: string;
}

export interface TaskProgressResult {
  readonly taskId: TaskId;
  readonly status: TaskStatus;
  readonly progress: number; // 0-100
  readonly message: string;
  readonly startTime: Timestamp;
  readonly endTime?: Timestamp;
  readonly result?: unknown;
  readonly error?: string;
}

/**
 * Common query parameters
 */
export interface CommonQueryParams extends PaginationParams {
  readonly filter?: string;
  readonly search?: string;
  readonly fields?: string;
}

/**
 * Device query parameters
 */
export interface DeviceQueryParams extends CommonQueryParams {
  readonly type?: string;
  readonly status?: DeviceStatus;
  readonly domainId?: string;
}

/**
 * Device creation request payload
 */
export interface DeviceCreateRequest {
  readonly Name: string;
  readonly PluginKey: string;
  readonly PluginFields: readonly PluginField[];
  readonly Address: string;
  readonly Protocol: string;
  readonly DomainID?: number;
  readonly CredentialID?: number;
  readonly Disabled?: boolean;
  readonly Description?: string;
  readonly NotificationEmails?: readonly string[];
  readonly Monitor?: DeviceMonitor;
  readonly AssetFields?: readonly AssetField[];
  readonly BackupSchedules?: readonly BackupSchedule[];
  readonly ManualConfigTypes?: readonly string[];
  readonly BackupPrefix?: string;
  readonly FailurePolicy?: FailurePolicy;
  readonly PolicyIDs?: readonly number[];
  readonly UseAutoApply?: boolean;
  readonly LabelIDs?: readonly number[];
}

/**
 * Device update request payload (partial updates)
 */
export interface DeviceUpdateRequest {
  readonly name?: string;
  readonly type?: string;
  readonly ipAddress?: string;
  readonly hostname?: string;
  readonly credentials?: {
    readonly username?: string;
    readonly password?: string;
  };
  readonly description?: string;
  readonly enabled?: boolean;
  readonly tags?: readonly string[];
  readonly location?: string;
  readonly model?: string;
}

/**
 * Backup query parameters
 */
export interface BackupQueryParams extends CommonQueryParams {
  readonly deviceId?: DeviceId;
  readonly status?: BackupStatus;
  readonly dateFrom?: Timestamp;
  readonly dateTo?: Timestamp;
}

/**
 * Type guards and utilities
 */
export const isTaskStatus = (value: unknown): value is TaskStatus => {
  return typeof value === 'string' && 
    ['pending', 'running', 'completed', 'failed', 'cancelled', 'timeout'].includes(value);
};

export const isDeviceStatus = (value: unknown): value is DeviceStatus => {
  return typeof value === 'string' && 
    ['online', 'offline', 'unknown', 'maintenance'].includes(value);
};

export const isBackupStatus = (value: unknown): value is BackupStatus => {
  return typeof value === 'string' && 
    ['completed', 'failed', 'in_progress', 'cancelled'].includes(value);
};

/**
 * Utility type for partial updates
 */
export type PartialUpdate<T> = {
  readonly [P in keyof T]?: T[P];
};

/**
 * Utility type for required fields
 */
export type RequiredFields<T, K extends keyof T> = T & Required<Pick<T, K>>;

/**
 * Endpoint operation types
 */
export type GetOperation = {
  readonly method: 'get';
  readonly path: string;
  readonly parameters?: Record<string, unknown>;
};

export type PostOperation = {
  readonly method: 'post';
  readonly path: string;
  readonly parameters?: Record<string, unknown>;
  readonly body?: unknown;
};

export type PutOperation = {
  readonly method: 'put';
  readonly path: string;
  readonly parameters?: Record<string, unknown>;
  readonly body?: unknown;
};

export type DeleteOperation = {
  readonly method: 'delete';
  readonly path: string;
  readonly parameters?: Record<string, unknown>;
};

/**
 * API tag types for organizing endpoints
 */
export type ApiTag = 'Agent' | 'Agent/Debug' | 'Agent/Remote' | 'Command' | 'Command/Output' | 'Command/Schedule' | 'Command/Variables' | 'Credential' | 'Credential/Bulk' | 'Credential/Provider/CyberArk' | 'Backup' | 'Device' | 'Device/Backup' | 'Device/BulkEdit' | 'Device/BulkCreate' | 'Dictionary' | 'Discovery' | 'Discovery/Device' | 'Domain' | 'Download';

/**
 * End of generated types
 */